baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Bantay'
theme = 'bantay'

# `copyright` will render in footer as safe HTML
copyright = '&copy;2023 Gil Locaylocay Caley'
sectionPagesMenu = 'main'

[permalinks]
  [permalinks.page]
    blog = '/post/:slug/'
    poetry = '/poem/:slug/'

[params]
  mainSections = ['blog', 'poetry', 'essays']

  # Sidebar
  # `about` will render in sidebar as safe HTML
  [params.sidebar]
    about = 'Gil Locaylocay Caley is a 24-year-old developer based in Dallas-Ft. Worth. [he/they](https://my.pronouns.page/are/he&they)'

    # Sidebar links
    [[params.sidebar.links]]
      name = "Example link"
      url = "/"
      weight = 1

    [[params.sidebar.links]]
      name = "Dxample link"
      url = "/"
      weight = 1

    [[params.sidebar.links]]
      name = "Fxample link"
      url = "/"
      weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true